# Generated by Django 3.2.5 on 2021-08-19 12:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls_count', models.IntegerField(blank=True, default=0)),
                ('client_address', models.CharField(blank=True, max_length=15)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_input', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only alphabetic and: ":", "/", "." characters are allowed in URL to shorten.', regex='^[a-zA-Z:/.]*$')])),
                ('url_output', models.CharField(blank=True, max_length=255, unique=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(blank=True, default=datetime.datetime(2055, 12, 11, 23, 7, tzinfo=utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShortenerIndex.client')),
            ],
        ),
    ]
