# Generated by Django 3.2.5 on 2021-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerIndex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='urls_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
