"""
Django settings for LinkShortener project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import string
from os.path import join, dirname
from pathlib import Path
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv, find_dotenv
import random

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


POSTGRES_USER = None
POSTGRES_PASSWORD = None
load_dotenv(find_dotenv('variables.env'))

if os.path.exists('variables.env'):
    SECRET_KEY = str(os.getenv('SECRET_KEY'))
    POSTGRES_USER = str(os.getenv('POSTGRES_USER'))
    POSTGRES_PASSWORD = str(os.getenv('POSTGRES_PASSWORD'))
else:
    with open('variables.env', 'w') as f:
        rand_key = get_random_secret_key()
        generate_pass = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(7))
        f.write(f'POSTGRES_USER=db_admin\n')
        f.write(f'POSTGRES_PASSWORD={generate_pass}\n')
        f.write(f'SECRET_KEY={rand_key}\n')
    load_dotenv(find_dotenv('variables.env'))
    SECRET_KEY = str(os.getenv('SECRET_KEY'))
    POSTGRES_USER = str(os.getenv('POSTGRES_USER'))
    POSTGRES_PASSWORD = str(os.getenv('POSTGRES_PASSWORD'))

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = []

DEFAULT_DOMAIN = 'http://localhost:8000/'

# Application definition

INSTALLED_APPS = [
    'ShortenerIndex',
    'API',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LinkShortener.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LinkShortener.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': 'postgres',

        'USER': POSTGRES_USER,

        'PASSWORD': POSTGRES_PASSWORD,

        'HOST': 'db',

        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'



STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
